version: '3.8'

services:
  db:
    image: postgres:15
    restart: always  # Автоперезапуск при сбое
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    command: ["bash", "-c", "python manage.py wait_for_db && python manage.py runserver 0.0.0.0:8000"]

  celery:
    build: .
    restart: always
    depends_on:
      - redis
      - web
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: ["celery", "-A", "netology_pd_diplom", "worker", "--loglevel=info"]

  celery-beat:
    build: .
    restart: always
    depends_on:
      - web
      - celery
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: ["celery", "-A", "netology_pd_diplom", "beat", "--loglevel=info"]

volumes:
  pgdata:
